-- 原 engine / database 硬编码别名全量入库 alias_config（可重复执行 INSERT OR IGNORE）
-- AMOUNT：算法词「各」及别名
INSERT OR IGNORE INTO alias_config (category, standard_word, alias_word) VALUES
  ('AMOUNT', '各', '各'),
  ('AMOUNT', '各', '各数'),
  ('AMOUNT', '各', '个数'),
  ('AMOUNT', '各', '个'),
  ('AMOUNT', '各', '各组'),
  ('AMOUNT', '各', '每个'),
  ('AMOUNT', '各', '各位'),
  ('AMOUNT', '各', '各个'),
  ('AMOUNT', '各', '各位数'),
  ('AMOUNT', '各', '各号'),
  ('AMOUNT', '各', '每号'),
  ('AMOUNT', '各', '每各'),
  ('AMOUNT', '各', '个个'),
  ('AMOUNT', '各', '每个号'),
  ('AMOUNT', '各', '一个'),
  ('AMOUNT', '加', '加'),
  ('AMOUNT', '减', '减'),
  ('AMOUNT', '乘', '乘'),
  ('AMOUNT', '除', '除'),
  ('AMOUNT', '+', '+'),
  ('AMOUNT', '*', '*'),
  ('AMOUNT', '/', '/'),
  ('AMOUNT', 'x', 'x'),
  ('AMOUNT', 'X', 'X');

-- SET：金额单位 / 装饰单位（元及别名）
INSERT OR IGNORE INTO alias_config (category, standard_word, alias_word) VALUES
  ('SET', '元', '元'),
  ('SET', '元', '米'),
  ('SET', '元', '闷'),
  ('SET', '元', '焖'),
  ('SET', '元', '蒙'),
  ('SET', '元', 'A'),
  ('SET', '元', 'a'),
  ('SET', '元', '块'),
  ('SET', '元', '角'),
  ('SET', '元', '分'),
  ('SET', '元', '斤'),
  ('SET', '元', '刀'),
  ('SET', '元', '整');

-- REGION：渠道（与 ensureMacauGuideSynonyms / cmd_channels 一致）
INSERT OR IGNORE INTO alias_config (category, standard_word, alias_word) VALUES
  ('REGION', '新澳门', '新澳门'),
  ('REGION', '新澳门', '新奥'),
  ('REGION', '新澳门', '新澳'),
  ('REGION', '新澳门', '新噢'),
  ('REGION', '新澳门', '新'),
  ('REGION', '新澳门', '澳'),
  ('REGION', '新澳门', '奥'),
  ('REGION', '新澳门', '噢'),
  ('REGION', '新澳门', '门'),
  ('REGION', '老澳门', '老澳门'),
  ('REGION', '老澳门', '老奥'),
  ('REGION', '老澳门', '老澳'),
  ('REGION', '香港', '香港'),
  ('REGION', '香港', '港'),
  ('REGION', '香港', '香'),
  ('REGION', '越南', '越南'),
  ('REGION', '越南', '越');

-- PLAY：玩法分类别名（连肖 / 平特三连 / 三四连肖等）
INSERT OR IGNORE INTO alias_config (category, standard_word, alias_word) VALUES
  ('PLAY', '连肖', '连肖'),
  ('PLAY', '连肖', '二连'),
  ('PLAY', '连肖', '二连肖'),
  ('PLAY', '三连肖', '三连肖'),
  ('PLAY', '三连肖', '三连'),
  ('PLAY', '四连肖', '四连肖'),
  ('PLAY', '四连肖', '四连'),
  ('PLAY', '五连肖', '五连肖'),
  ('PLAY', '五连肖', '五连'),
  ('PLAY', '连码', '连码'),
  ('PLAY', '连码', '平特连码'),
  ('PLAY', '平特三连', '平特三连'),
  ('PLAY', '平特三连', '平特三连肖'),
  ('PLAY', '三连肖', '三友'),
  ('PLAY', '三连肖', '三有'),
  ('PLAY', '四连肖', '四友'),
  ('PLAY', '四连肖', '四有'),
  ('PLAY', '特', '特'),
  ('PLAY', '特', '特码'),
  ('PLAY', '特肖', '特肖'),
  ('PLAY', '特肖马', '特肖马'),
  ('PLAY', '平特', '平特'),
  ('PLAY', '平特马', '平特马'),
  ('PLAY', '单双', '单双'),
  ('PLAY', '半波', '半波'),
  ('PLAY', '波段', '波段'),
  ('PLAY', '合单双', '合单双'),
  ('PLAY', '平尾', '平尾'),
  ('PLAY', '平尾0尾', '平尾0尾');

-- INSTRUCTION：管理指令（原 DEFAULT_INSTRUCTION_ALIASES + seedInstructionSynonyms）
INSERT OR IGNORE INTO alias_config (category, standard_word, alias_word) VALUES
  ('INSTRUCTION', 'help', '帮助'),
  ('INSTRUCTION', 'help', '菜单'),
  ('INSTRUCTION', 'help', '指令'),
  ('INSTRUCTION', 'help', '指令帮助'),
  ('INSTRUCTION', 'help', '使用帮助'),
  ('INSTRUCTION', 'help', '报表帮助'),
  ('INSTRUCTION', 'help', '报表指令'),
  ('INSTRUCTION', 'clear_order', '清空订单'),
  ('INSTRUCTION', 'clear_order', '清空'),
  ('INSTRUCTION', 'clear_order', '清零'),
  ('INSTRUCTION', 'clear_order', '清单'),
  ('INSTRUCTION', 'clear_order', '清空当前订单'),
  ('INSTRUCTION', 'order_query', '查单'),
  ('INSTRUCTION', 'order_query', '查订单'),
  ('INSTRUCTION', 'order_query', '查询订单'),
  ('INSTRUCTION', 'order_query_detail', '查明细单'),
  ('INSTRUCTION', 'order_query_detail', '查订单明细'),
  ('INSTRUCTION', 'query_group_config', '查询群配置'),
  ('INSTRUCTION', 'query_group_config', '查群配置'),
  ('INSTRUCTION', 'query_group_config', '群配置查询'),
  ('INSTRUCTION', 'query_group_config', '查看群配置'),
  ('INSTRUCTION', 'query_group_config', '查设置'),
  ('INSTRUCTION', 'query_group_config', '查询设置'),
  ('INSTRUCTION', 'odds_table', '赔率表'),
  ('INSTRUCTION', 'odds_table', '查询赔率表'),
  ('INSTRUCTION', 'odds_table', '查赔率表'),
  ('INSTRUCTION', 'odds_table', '查看赔率表'),
  ('INSTRUCTION', 'odds_table', '查赔率'),
  ('INSTRUCTION', 'list_play_modes', '玩法'),
  ('INSTRUCTION', 'list_play_modes', '查玩法'),
  ('INSTRUCTION', 'list_play_modes', '查询玩法'),
  ('INSTRUCTION', 'group_config_mark', '群配置'),
  ('INSTRUCTION', 'group_config_mark', '设置费率'),
  ('INSTRUCTION', 'group_config_mark', '设置水率'),
  ('INSTRUCTION', 'group_config_mark', '群设置'),
  ('INSTRUCTION', 'group_config_mark', '配置'),
  ('INSTRUCTION', 'group_config_mark', '设置'),
  ('INSTRUCTION', 'set_var', '设变量'),
  ('INSTRUCTION', 'group_report', '报表'),
  ('INSTRUCTION', 'settlement_summary', '总结');
